

import { Prisma } from '@prisma/client';

export const productData: Prisma.ProductsCreateInput[] = [
	// PELELE
	{
		name: 'Pelele algodón azul',
		stock: 20,
		category: 'pelele',
		classification: 'niño',
		rating: 4.5,
		image:
			'https://cdn.jsdelivr.net/gh/faker-js/assets-person-portrait/male/512/21.jpg',
		discount: 'FIFTY',
		tags: 'pelele,algodón,azul,niño',
		age_range: '0-3',
		material: 'Algodón',
		price: 890,
	},
	{
		name: 'Pelele con estampado animal',
		stock: 15,
		category: 'pelele',
		classification: 'niña',
		rating: 4.2,
		image:
			'https://cdn.jsdelivr.net/gh/faker-js/assets-person-portrait/female/512/31.jpg',
		discount: 'FORTY',
		tags: 'pelele,estampado,animal,niña',
		age_range: '3-6',
		material: 'Algodón',
		price: 950,
	},
	{
		name: 'Pelele polar invierno',
		stock: 10,
		category: 'pelele',
		classification: 'niño',
		rating: 4.7,
		image:
			'https://cdn.jsdelivr.net/gh/faker-js/assets-person-portrait/male/512/41.jpg',
		discount: null,
		tags: 'pelele,polar,invierno,niño',
		age_range: '6-9',
		material: 'Polar',
		price: 1050,
	},

	// VESTIDO
	{
		name: 'Vestido flores primavera',
		stock: 18,
		category: 'vestido',
		classification: 'niña',
		rating: 4.8,
		image:
			'https://cdn.jsdelivr.net/gh/faker-js/assets-person-portrait/female/512/12.jpg',
		discount: 'THIRTY',
		tags: 'vestido,flores,primavera,niña',
		age_range: '2-3',
		material: 'Lino',
		price: 1200,
	},
	{
		name: 'Vestido denim casual',
		stock: 12,
		category: 'vestido',
		classification: 'niña',
		rating: 4.6,
		image:
			'https://cdn.jsdelivr.net/gh/faker-js/assets-person-portrait/female/512/22.jpg',
		discount: null,
		tags: 'vestido,denim,casual,niña',
		age_range: '3-4',
		material: 'Denim',
		price: 1350,
	},
	{
		name: 'Vestido fiesta rosa',
		stock: 8,
		category: 'vestido',
		classification: 'niña',
		rating: 4.9,
		image:
			'https://cdn.jsdelivr.net/gh/faker-js/assets-person-portrait/female/512/32.jpg',
		discount: 'FIFTY',
		tags: 'vestido,fiesta,rosa,niña',
		age_range: '4-5',
		material: 'Seda',
		price: 1800,
	},

	// CAMISA
	{
		name: 'Camisa lino manga corta',
		stock: 25,
		category: 'camisa',
		classification: 'niño',
		rating: 4.3,
		image:
			'https://cdn.jsdelivr.net/gh/faker-js/assets-person-portrait/male/512/13.jpg',
		discount: null,
		tags: 'camisa,lino,manga corta,niño',
		age_range: '3-4',
		material: 'Lino',
		price: 950,
	},
	{
		name: 'Camisa cuadros clásica',
		stock: 17,
		category: 'camisa',
		classification: 'niño',
		rating: 4.1,
		image:
			'https://cdn.jsdelivr.net/gh/faker-js/assets-person-portrait/male/512/23.jpg',
		discount: 'FORTY',
		tags: 'camisa,cuadros,clásica,niño',
		age_range: '4-5',
		material: 'Algodón',
		price: 990,
	},
	{
		name: 'Camisa blanca elegante',
		stock: 14,
		category: 'camisa',
		classification: 'niña',
		rating: 4.7,
		image:
			'https://cdn.jsdelivr.net/gh/faker-js/assets-person-portrait/female/512/43.jpg',
		discount: 'THIRTY',
		tags: 'camisa,blanca,elegante,niña',
		age_range: '5-6',
		material: 'Algodón',
		price: 1100,
	},

	// SHORT
	{
		name: 'Short deportivo azul',
		stock: 30,
		category: 'short',
		classification: 'niño',
		rating: 4.4,
		image:
			'https://cdn.jsdelivr.net/gh/faker-js/assets-person-portrait/male/512/15.jpg',
		discount: null,
		tags: 'short,deportivo,azul,niño',
		age_range: '3-4',
		material: 'Poliéster',
		price: 700,
	},
	{
		name: 'Short flores verano',
		stock: 22,
		category: 'short',
		classification: 'niña',
		rating: 4.6,
		image:
			'https://cdn.jsdelivr.net/gh/faker-js/assets-person-portrait/female/512/25.jpg',
		discount: 'FIFTY',
		tags: 'short,flores,verano,niña',
		age_range: '2-3',
		material: 'Algodón',
		price: 750,
	},
	{
		name: 'Short básico blanco',
		stock: 18,
		category: 'short',
		classification: 'niño',
		rating: 4.2,
		image:
			'https://cdn.jsdelivr.net/gh/faker-js/assets-person-portrait/male/512/35.jpg',
		discount: null,
		tags: 'short,básico,blanco,niño',
		age_range: '4-5',
		material: 'Algodón',
		price: 690,
	},

	// CUBREPAÑAL
	{
		name: 'Cubrepañal rayas',
		stock: 16,
		category: 'cubrepañal',
		classification: 'niño',
		rating: 4.5,
		image:
			'https://cdn.jsdelivr.net/gh/faker-js/assets-person-portrait/male/512/17.jpg',
		discount: 'THIRTY',
		tags: 'cubrepañal,rayas,niño',
		age_range: '1-2',
		material: 'Algodón',
		price: 600,
	},
	{
		name: 'Cubrepañal flores',
		stock: 14,
		category: 'cubrepañal',
		classification: 'niña',
		rating: 4.7,
		image:
			'https://cdn.jsdelivr.net/gh/faker-js/assets-person-portrait/female/512/27.jpg',
		discount: null,
		tags: 'cubrepañal,flores,niña',
		age_range: '2-3',
		material: 'Algodón',
		price: 650,
	},
	{
		name: 'Cubrepañal básico blanco',
		stock: 20,
		category: 'cubrepañal',
		classification: 'niño',
		rating: 4.3,
		image:
			'https://cdn.jsdelivr.net/gh/faker-js/assets-person-portrait/male/512/37.jpg',
		discount: 'FIFTY',
		tags: 'cubrepañal,básico,blanco,niño',
		age_range: '3-4',
		material: 'Algodón',
		price: 620,
	},

	// PETO
	{
		name: 'Peto vaquero clásico',
		stock: 12,
		category: 'peto',
		classification: 'niño',
		rating: 4.6,
		image:
			'https://cdn.jsdelivr.net/gh/faker-js/assets-person-portrait/male/512/19.jpg',
		discount: null,
		tags: 'peto,vaquero,clásico,niño',
		age_range: '2-3',
		material: 'Denim',
		price: 1300,
	},
	{
		name: 'Peto rosa algodón',
		stock: 10,
		category: 'peto',
		classification: 'niña',
		rating: 4.8,
		image:
			'https://cdn.jsdelivr.net/gh/faker-js/assets-person-portrait/female/512/29.jpg',
		discount: 'FORTY',
		tags: 'peto,rosa,algodón,niña',
		age_range: '3-4',
		material: 'Algodón',
		price: 1250,
	},
	{
		name: 'Peto corto verano',
		stock: 14,
		category: 'peto',
		classification: 'niño',
		rating: 4.4,
		image:
			'https://cdn.jsdelivr.net/gh/faker-js/assets-person-portrait/male/512/39.jpg',
		discount: 'THIRTY',
		tags: 'peto,corto,verano,niño',
		age_range: '4-5',
		material: 'Lino',
		price: 1200,
	},

	// RANITA
	{
		name: 'Ranita básica azul',
		stock: 18,
		category: 'ranita',
		classification: 'niño',
		rating: 4.5,
		image:
			'https://cdn.jsdelivr.net/gh/faker-js/assets-person-portrait/male/512/11.jpg',
		discount: null,
		tags: 'ranita,básica,azul,niño',
		age_range: '1-2',
		material: 'Algodón',
		price: 800,
	},
	{
		name: 'Ranita estampada flores',
		stock: 15,
		category: 'ranita',
		classification: 'niña',
		rating: 4.7,
		image:
			'https://cdn.jsdelivr.net/gh/faker-js/assets-person-portrait/female/512/21.jpg',
		discount: 'FIFTY',
		tags: 'ranita,estampada,flores,niña',
		age_range: '2-3',
		material: 'Algodón',
		price: 850,
	},
	{
		name: 'Ranita polar invierno',
		stock: 12,
		category: 'ranita',
		classification: 'niño',
		rating: 4.3,
		image:
			'https://cdn.jsdelivr.net/gh/faker-js/assets-person-portrait/male/512/31.jpg',
		discount: 'THIRTY',
		tags: 'ranita,polar,invierno,niño',
		age_range: '3-4',
		material: 'Polar',
		price: 900,
	},

	// COMPLEMENTO
	{
		name: 'Gorro algodón azul',
		stock: 25,
		category: 'complemento',
		classification: 'niño',
		rating: 4.6,
		image:
			'https://cdn.jsdelivr.net/gh/faker-js/assets-person-portrait/male/512/27.jpg',
		discount: null,
		tags: 'gorro,algodón,azul,niño',
		age_range: '0-3',
		material: 'Algodón',
		price: 300,
	},
	{
		name: 'Cinta para el cabello rosa',
		stock: 20,
		category: 'complemento',
		classification: 'niña',
		rating: 4.8,
		image:
			'https://cdn.jsdelivr.net/gh/faker-js/assets-person-portrait/female/512/37.jpg',
		discount: 'FORTY',
		tags: 'cinta,cabello,rosa,niña',
		age_range: '1-2',
		material: 'Algodón',
		price: 250,
	},
	{
		name: 'Babero impermeable',
		stock: 30,
		category: 'complemento',
		classification: 'niño',
		rating: 4.4,
		image:
			'https://cdn.jsdelivr.net/gh/faker-js/assets-person-portrait/male/512/47.jpg',
		discount: 'THIRTY',
		tags: 'babero,impermeable,niño',
		age_range: '0-1',
		material: 'Poliéster',
		price: 200,
	},
];
